@startuml

title "로그인"
actor User as T
participant WebClient as C
participant "SchoolManager Server" as S
database DataBase as DB
T -> C: GET/
activate C
C -> S:static asset 요청(HTML/CSS 등)
activate S
S --> C:HTML/CSS 등 응답
deactivate S
C -> C: 로그인 페이지로 redirection
C --> T: 로그인 페이지
T -> C: 1. 로그인 요청
C -> S: POST /login
activate S
S -> S: 인증 or guid
S -> DB: request(/login)
activate DB
DB --> S: response(TeacherInfo)
deactivate DB
S --> C: Success
deactivate S
C -> C: 로그인 정보 저장
C -> C: 클래스 페이지 redirection
C --> T: 클래스 페이지

newpage 2. 클래스 생성 Page
alt 클래스를 만든적 없는 경우
  T -> C: 클래스 생성 페이지
  C -> S++: Put /classes
  S -> S: 클래스 uid
  S -> DB++: 클래스 item 생성
  DB --> S--: resposne(classInfo)
  return Success
  C -> C: 클래스 정보 저장
  C -> C: 클래스 모음 redirection
  C-->T: 클래스 모음 페이지
else 클래스가 있는 경우
  C->C: 클래스 모음 redirection
  return 클래스 모음 페이지
end
@enduml